"""Add invite status enum and other changes

Revision ID: 84944c6098f7
Revises: e9d2c52545a2
Create Date: 2025-07-28 14:01:37.862001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84944c6098f7'
down_revision = 'e9d2c52545a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_column('delivery_channel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_channel', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
